### ISSUE TITLE
[Bug] 清退用户失败

### ISSUE THREAD

**Issue by smartcatboy** [smartcatboy/compose#4]
错误日志如下：

```log
backend_1   | INFO:     192.168.80.6:47048 - "DELETE /api/v1/users/3 HTTP/1.0" 500 Internal Server Error
backend_1   | ERROR:    Exception in ASGI application
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi
backend_1   |     result = await app(self.scope, self.receive, self.send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
backend_1   |     return await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
backend_1   |     await super().__call__(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
backend_1   |     await self.middleware_stack(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
backend_1   |     raise exc from None
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
backend_1   |     await self.app(scope, receive, _send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
backend_1   |     response = await self.dispatch_func(request, self.call_next)
backend_1   |   File "/app/app/main.py", line 73, in db_session_middleware
backend_1   |     response = await call_next(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
backend_1   |     task.result()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 25, in __call__
backend_1   |     response = await self.dispatch_func(request, self.call_next)
backend_1   |   File "/app/app/main.py", line 65, in sentry_exception
backend_1   |     raise e
backend_1   |   File "/app/app/main.py", line 57, in sentry_exception
backend_1   |     response = await call_next(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 45, in call_next
backend_1   |     task.result()
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 38, in coro
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
backend_1   |     await self.simple_response(scope, receive, send, request_headers=headers)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
backend_1   |     raise exc from None
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
backend_1   |     await self.app(scope, receive, sender)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
backend_1   |     await route.handle(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
backend_1   |     await self.app(scope, receive, send)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
backend_1   |     response = await func(request)
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
backend_1   |     raw_response = await run_endpoint_function(
backend_1   |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
backend_1   |     return await dependant.call(**values)
backend_1   |   File "/app/app/api/v1/users.py", line 209, in user_delete
backend_1   |     PortUsageEdit(
backend_1   |   File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
backend_1   |     raise validation_error
backend_1   | pydantic.error_wrappers.ValidationError: 1 validation error for PortUsageEdit
backend_1   | port_id
backend_1   |   field required (type=value_error.missing)
backend_1   | INFO:     192.168.80.6:47056 - "GET /api/v2/users?page=0&size=5 HTTP/1.0" 200 OK
```

**Comment by smartcatboy** [comment]
已修复于 [#c73fdb0](https://github.com/smartcatboy/backend/commit/c73fdb0a0cd1393569a6b57d88c088c8983c1abb) 。
